# Generated by Django 4.2.21 on 2025-05-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=255, unique=True, verbose_name='Tên Chủ đề')),
            ],
            options={
                'verbose_name': 'Chủ đề',
                'verbose_name_plural': 'Các Chủ đề',
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=50, unique=True, verbose_name='Mã Loại Câu Hỏi')),
                ('type_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả Loại Câu Hỏi')),
            ],
            options={
                'verbose_name': 'Loại Câu Hỏi',
                'verbose_name_plural': 'Các Loại Câu Hỏi',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Nội dung Câu Hỏi')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Giải thích')),
                ('options_mc', models.JSONField(blank=True, null=True, verbose_name='Lựa chọn Trắc nghiệm (JSON Array)')),
                ('correct_answer_mc_single', models.IntegerField(blank=True, null=True, verbose_name='Đáp án Trắc nghiệm Chọn 1 / Đúng-Sai đơn')),
                ('correct_answers_mc_multiple', models.JSONField(blank=True, null=True, verbose_name='Đáp án Trắc nghiệm Chọn nhiều (JSON Array)')),
                ('statements_tf_table', models.JSONField(blank=True, null=True, verbose_name='Khẳng định Đúng-Sai Bảng (JSON Array)')),
                ('correct_answers_tf_table', models.JSONField(blank=True, null=True, verbose_name='Đáp án Đúng-Sai Bảng (JSON Array)')),
                ('draggable_items_dd', models.JSONField(blank=True, null=True, verbose_name='Mục Kéo (JSON Array)')),
                ('drop_zone_labels_dd', models.JSONField(blank=True, null=True, verbose_name='Nhãn Vùng Thả (JSON Array)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.module', verbose_name='Chủ đề')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.questiontype', verbose_name='Loại Câu Hỏi')),
            ],
            options={
                'verbose_name': 'Câu Hỏi',
                'verbose_name_plural': 'Các Câu Hỏi',
                'ordering': ['-created_at'],
            },
        ),
    ]
